comments/urls.py
from django.urls import path, include
from .views import comment_thread, confirm_delete

app_name = 'comments'
urlpatterns = [
    path('<int:pk>/', comment_thread, name='thread'),
    path('<int:pk>/delete/', confirm_delete, name='delete'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import (
    login_view,
    logout_view,
    register_view
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comments/', include('comments.urls')),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('', include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.post_list, name='list'),
    path('create/', views.post_create, name='create'),
    path('<slug:slug>/', views.post_detail, name='detail'),
    path('<slug:slug>/update/', views.post_update),
    path('<slug:slug>/delete/', views.post_delete),
]

posts/models.py
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from django.utils import timezone
from django.db.models.signals import pre_save
from markdown_deux import markdown
from comments.models import Comment
from .utils import get_read_time


# Create your models here.
# Post.objects.all()
# Post.objects.create()
class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.FileField(null=True, blank=True)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'slug': self.slug})

    def get_markdown(self):
        content = self.content
        # Converting content into markdown
        return mark_safe(markdown(content))

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by('-id')
    exist = qs.exists()
    if exist:
        new_slug = f'{slug}-{qs.first().id}'
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var


pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms
from .models import Post
from pagedown.widgets import PagedownWidget


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'draft', 'publish']

posts/views.py
from urllib.parse import quote_plus
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, Http404
from django.utils import timezone
from django.core.paginator import Paginator
from django.db.models import Q
from .models import Post
from .forms import PostForm
from comments.models import Comment
from comments.forms import CommentForm


@login_required
def post_create(request):

    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Successfuly Created")
        return HttpResponseRedirect(f'/{instance.slug}/')

    button_variables = "Create"
    context = {
        'form': form,
        'button_variables': button_variables
    }
    return render(request, 'post_form.html', context)


def post_detail(request, slug):
    today = timezone.now().date()
    instance = get_object_or_404(Post, slug=slug)
    if instance.publish > timezone.now().date() or instance.draft:
        if not request.user.is_authenticated or not request.user.is_staff or not request.user.is_superuser:
            raise Http404

    initial_data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id
    }
    comment_form = CommentForm(request.POST or None, initial=initial_data)
    if comment_form.is_valid():
        c_type = comment_form.cleaned_data.get("content_type")

        content_type = ContentType.objects.get(model=c_type)
        object_id = comment_form.cleaned_data.get("object_id")
        content = comment_form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None

        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()

        new_comment, created = Comment.objects.get_or_create(
            user=request.user,
            content_type=content_type,
            object_id=object_id,
            content=content,
            parent=parent_obj
        )

        return HttpResponseRedirect(f'/{instance.slug}/')

    comments = instance.comments
    share_string = quote_plus(instance.content)
    context = {
        "title": instance.title,
        "instance": instance,
        "share_string": share_string,
        "today": today,
        "comment_form": comment_form,
        "comments": comments,
    }
    return render(request, 'post_detail.html', context)


def post_list(request):
    today = timezone.now().date()
    query_list = Post.objects.active()

    if request.user.is_staff or request.user.is_superuser:
        query_list = Post.objects.all().order_by('-timestamp')

    search = request.GET.get('search')
    if search:
        query_list = query_list.filter(
            Q(title__icontains=search) or
            Q(content__icontains=search)
        ).distinct()
    paginator = Paginator(query_list, 6)
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    query_set = paginator.get_page(page)

    context = {
            "title": "My User List",
            "object_list": query_set,
            "page_request_var": page_request_var,
            "today": today
        }

    return render(request, 'post_list.html', context)


@login_required
def post_update(request, slug):

    instance = get_object_or_404(Post, slug=slug)

    if request.user == instance.user or request.user.is_superuser:
        form = PostForm(request.POST or None, request.FILES or None, instance=instance)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.success(request, "Post Updated")
            return HttpResponseRedirect(f'/{instance.slug}/')
    else:
        raise Http404("You Dont Have Permission to delete this post")

    button_variables = "Update"
    context = {
        "title": instance.title,
        "instance": instance,
        "button_variables": button_variables,
        "form": form
    }
    return render(request, 'post_form.html', context)


@login_required
def post_delete(request, slug):

    instance = get_object_or_404(Post, slug=slug)

    if request.user == instance.user or request.user.is_superuser:
        instance.delete()
        messages.success(request, "Successfuly Deleted")
        return redirect('posts:list')
    else:
        raise Http404("You Dont Have Permission to delete this post")

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>{% block title %} Django Blog {% endblock title %}</title>
    {% block extra_head %}{% endblock extra_head %}
</head>
<body>

<!--Post Comments-->
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/id_ID/sdk.js#xfbml=1&version=v4.0"></script>
{% include 'navbar.html' %}
{% include 'display_messages.html' %}

<div class="container">
    {% block content %}
    {% endblock content %}
</div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.7.0/marked.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $(".content-markdown").each(function(){
            var content = $(this).text()
            var markContent = marked(content)
            $(this).html(markContent)
        })

        $(".post-detail-img img").each(function(){
            $(this).addClass("img-fluid")
        })

        var contentInput = $("#id_content")

        function setContent(value){
            var markedContent = marked(value);
            $("#preview-content").html(markedContent)
            $("#preview-content img").each(function() {
                $(this).addClass("img-fluid")
            })
        }

        setContent(contentInput.val())

        contentInput.keyup(function(){
            var newContent = $(this).val()
            setContent(newContent)
        })

        var titleInput = $("#id_title")

        function setTitle(value){
            $("#preview-title").text(value)
        }
        setTitle(titleInput.val())

        titleInput.keyup(function() {
            newTitle = $(this).val()
            setTitle(newTitle)
        })

        $(".comment-reply-btn").click(function(event) {
            event.preventDefault();
            $(this).parent().next(".comment-reply").slideToggle();
        })
    })
</script>
</body>
</html>

templates/comment_thread.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    {{ instance.title }} |  {{ block.super }}
{% endblock title%}

{% block content %}

<div class="col-lg-6 col-md-12 col-sm-12 mt-4">
<h4>Comment Thread</h4>
        <blockquote class="five-border-left p-2">
            <p class="mb-0">{{ comment.content }}</p>
            <footer class="blockquote-footer">from: {{ comment.user }} on: {{ comment.timestamp|timesince }} ago |
                {% if comment.children.count > 0 %}
                    {{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %}
                {% endif %}
                {% if request.user == comment.user %}
                    <a href="{% url 'comments:delete' comment.id %}">Delete</a>
                {% endif %}
            </footer>
            <div>
                {% for child_comment in comment.children %}
                <blockquote class="five-border-left p-2">
                    <p class="mb-0">{{ child_comment.content }}</p>
                    <footer class="blockquote-footer">from: {{ child_comment.user }} on: {{ child_comment.timestamp|timesince }} ago
                        {% if request.user == comment.user %}
                        <a href="{% url 'comments:delete' child_comment.id %}">Delete</a>
                        {% endif %}
                    </footer>
                </blockquote>
                {% endfor %}
                {% if user.is_authenticated %}
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="hidden" name="parent_id" value="{{ comment.id }}">
                    <button class="btn btn-outline-info" type="submit">Reply Comment</button>
                </form>
                {% else %}
                <p>You Must Login to Comments</p>
                {% endif %}
            </div>
        </blockquote>
    <hr>
</div>

{% endblock content%}

templates/confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    {{ instance.title }} |  {{ block.super }}
{% endblock title%}

{% block content %}

<div class="col-lg-6 col-md-12 col-sm-12 mt-4">
    <form action="" method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete: "{{ object.content }}"?</p>
        <button class="btn btn-sm btn-outline-danger" type="submit">Delete</button>
        <a href="{% url 'comments:thread' object.pk %}" class="btn btn-sm btn-outline-primary">Cancel</a>
    </form>
</div>

{% endblock content %}

templates/display_messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-6 offset-md-3">
        <h1>{{ title }}</h1>
        <hr>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="{{ title }}" />
        </form>
    </div>
{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'posts:list' %}">Navbar</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'posts:list' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'posts:create' %}">Create</a>
      </li>
    </ul>
      <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="#">User: {{ request.user|capfirst }}</a>
          <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
          {% else %}
          <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
          {% endif %}
      </div>
  </div>
</nav>

templates/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    {{ instance.title }} |  {{ block.super }}
{% endblock title%}

{% block content %}
<div class="col-lg-6 col-md-12 col-sm-12">
    <div class="mt-4 mb-4">
        {% if instance.image %}
        <img src="{{ instance.image.url }}" class="img-fluid" alt="">
        {% endif %}
        <h2>{{ instance.title }}</h2>
        {% if instance.draft %}
        <span class="text-danger"> Draft </span>
        {% endif %}
        {% if instance.publish > today %}
        <span class="text-danger"> Future Post </span>
        {% endif %}
        <p class="text-muted mb-3">Author:
            {% if instance.user %}
                {{ instance.user }}
            {% else %}
                Anonymous
            {% endif %}
        </p>
        <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-width="" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
        <p><small>{{ instance.publish }}</small></p>
        <p><small>Read time: {% if instance.read_time <= 1 %} < 1 Minute {% else %} {{ instance.read_time }} Minutes {% endif %}</small></p>
    </div>

<!-- SHARE LINK -->

<!--    <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">-->
<!--    Facebook-->
<!--    </a>-->

<!--    <a href="https://twitter.com/home?status={{ share_string|truncatechars:80 }}%20{{ request.build_absolute_uri }}">-->
<!--    Twitter-->
<!--    </a>-->

<!--    <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ share_string|truncatechars:80 }}&source={{ request.build_absolute_uri }}">-->
<!--    Linkedin-->
<!--    </a>-->
    <div class="post-detail-img">{{ instance.get_markdown }}</div>

<hr>
    <p class="lead">Comments</p>
    {% if user.is_authenticated %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ comment_form|crispy }}
        <button class="btn btn-info" type="submit">Submit Comment</button>
    </form>
    {% else %}
    <p>You Must Login to Comment!</p>
    {% endif %}
    <hr>
    {% for comment in comments %}
        <blockquote class="five-border-left p-2">
            <p class="mb-0">{{ comment.content }}</p>
            <footer class="blockquote-footer">from: {{ comment.user }} on: {{ comment.timestamp|timesince }} ago |
                {% if comment.children.count > 0 %}
                    {{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %}
                {% endif %}
                <br>
                <a href="#" class="comment-reply-btn"> Reply </a>
                <a href="{% url 'comments:thread' comment.id %}"> Thread </a>
            </footer>
            <div class="comment-reply">
                    {% for child_comment in comment.children %}
                <blockquote class="five-border-left p-2">
                    <p class="mb-0">{{ child_comment.content }}</p>
                    <footer class="blockquote-footer">from: {{ child_comment.user }} on: {{ child_comment.timestamp|timesince }} ago</footer>
                </blockquote>
                {% endfor %}
                {% if user.is_authenticated %}
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ comment_form|crispy }}
                    <input type="hidden" name="parent_id" value="{{ comment.id }}">
                    <button class="btn btn-outline-info" type="submit">Reply Comment</button>
                </form>
                {% else %}
                <p>You Must Login to Reply</p>
                {% endif %}
            </div>

        </blockquote>
    <hr>
    {% endfor %}
</div>

{% endblock content%}

templates/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
<!-- For The Pagedown -->
{% block extra_head %}{{ form.media }}{% endblock extra_head %}
{% block content %}
<div class="row">
    <div class="col">
        <h1>Preview</h1>
        <hr>
        <h4 id="preview-title"></h4>
        <p id="preview-content"></p>
    </div>

    <div class="col">
        <h1>Form</h1>
        <hr>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="{{ button_variables }}" />
        </form>
    </div>
</div>
{% endblock content %}

templates/post_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container m-3 p-2">
    <h2>List All Post</h2>
    <small class="text-muted">Still Don't Have any Post, Sign Up Now and Share Your Stories</small>
    <div class="text-center form-inline mt-4">
        <form action="">
            <input class="form-control form-control-sm" name="search" type="text" placeholder="Search Posts"
                   value="{{ request.GET.search }}">
            <button class="btn btn-sm btn-primary" type="submit"><i class="fa fa-search"></i></button>
        </form>
    </div>
</div>
<div class="row card-deck">
    {% for object in object_list %}
    <div class="col-lg-8 col-md-6 col-sm-12">
        <div class="card mt-2 mb-2">
            {% if object.image %}
            <img src="{{ object.image.url }}" class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body post-detail-img">
                <h5 class="card-title"><a href="{% url 'posts:detail' object.slug %}">{{ object.title }}</a></h5>
                {% if object.draft %}
                <small class="d-block font-italic text-danger">Staff Only: Draft </small>
                {% endif %}
                {% if object.publish > today %}
                <small class="d-block font-italic text-danger">Staff Only: Future Post </small>
                {% endif %}
                <p class="card-text">{{ object.get_markdown|truncatechars_html:80 }}</p>
                <a href="{% url 'posts:detail' object.slug %}" class="btn btn-primary">View</a>
            </div>
            <div class="card-footer">
                <small class="text-muted">Published at : {{ object.publish }}
                    {% if object.user %}
                        By: {{ object.user }}
                    {% endif %}
                </small>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
    <div class="mx-auto">
        <div class="pagination centering mt-3 mb-3">
            <span class="step-links">
                {% if object_list.has_previous %}
                    <a href="?{{ page_request_var }}=1">&laquo; first</a>
                    <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
                </span>

                {% if object_list.has_next %}
                    <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">next</a>
                    <a href="?{{ page_request_var }}={{ object_list.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
{% endblock content %}